# Generated by Django 4.2.7 on 2024-03-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0031_alter_co_po_matrix_po1_alter_co_po_matrix_po10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=5)),
                ('semester', models.CharField(max_length=5)),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_code', models.CharField(max_length=10)),
                ('academic_year', models.CharField(max_length=10)),
            ],
        ),
    ]
